version: '3.8'
services:

  toolbox-front:
    image: oliver33221/datasciencetoolboxmain:latest
    container_name: toolbox-front
    ports:
     - "80:80"

  toolbox-rstudio-service:
    image: rocker/rstudio
    container_name: toolbox-rstudio
    environment:
      DISABLE_AUTH: "true"
    ports:
     - "8787:8787"

  toolbox-orange-service:
    image: acopar/orange-docker
    container_name: toolbox-orange
    ports:
      - "6901:6901"
      - "5901:5901"
  
  toolbox-markdown-dillinger-service:
    image: ghcr.io/linuxserver/dillinger
    container_name: toolbox-markdown
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    ports:
      - "8080:8080"
    restart: unless-stopped

  toolbox-jupyter-service:
    image: oliver33221/base-note-new:latest
    container_name: toolbox-jupyter
    ports:
      - "8888:8888"

  toolbox-vscode-service:
    image: ghcr.io/linuxserver/code-server
    container_name: toolbox-code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PROXY_DOMAIN=code-server.my.domain #optional
    volumes:
      - /path/to/appdata/config:/config
    ports:
      - 8443:8443
    restart: unless-stopped

  toolbox-spyder-service:
    image: oliver33221/spyder:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: toolbox-spyder


  toolbox-git-service:
    image: theasp/novnc
    ports: 
      - "8008:8080"
    container_name: toolbox-git

  toolbox-hadoop-service:
    image: oliver33221/hadoopnvc:latest
    ports:
      - 8081:8080
      - 8042:8042
      - 8088:8088
      - 19888:19888
      - 50070:50070
      - 50075:50075

    container_name: toolbox-hadoop

  toolbox-spark-service-master:
    image: oliver33221/sparknvc
    hostname: master
    environment:
      MASTER: spark://master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: localhost
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8082:8080
    volumes:
      - ./conf/master:/conf
      - ./data:/tmp/data
    container_name: toolbox-spark-master

  toolbox-spark-service-worker:
    image: gettyimages/spark
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    hostname: worker
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8085
      SPARK_PUBLIC_DNS: localhost
    links:
      - toolbox-spark-service-master
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 8881
    ports:
      - 8085:8085
    volumes:
      - ./conf/worker:/conf
      - ./data:/tmp/data  
    container_name: toolbox-spark-worker

  toolbox-tensorflow-service:
    image: oliver33221/tensorflownvc
    ports:
      - 8083:8080
    container_name: toolbox-tensorflow




